### ISSUE TITLE
Это круто!

### ISSUE THREAD

**Issue by pivolan** [kochetovdv/proxyapi-bot#1]
Отличный продукт. Можете подсказать, токены будут считаться на каждый запрос со всеми инструкциями? Или инструкции только один раз будут считаться при запросах?

Т.к. обычный способ через чат, считает весь контекст на каждый запрос, что получается довольно накладно. Как это работает здесь?

есть ли у вас рабочий бот в телеграмме как демо версия для пробы?

**Comment by kochetovdv** [comment]
>  токены будут считаться на каждый запрос со всеми инструкциями? Или инструкции только один раз будут считаться при запросах?

При создании бота вы задаете инструкции и загружаете файлы в хранилище для последующей их векторизации. Это тарифицируется один раз.
Текущая реализация создает каждый раз нового ассистента, поэтому если сервис перезапускать, то вы каждый раз будете платить за создание.
В дальнейшем уже тарифицируются только токены ответов (каждого по отдельности). Итоговый ответ складывается из суммы ответов (SSE-вещание).

> есть ли у вас рабочий бот в телеграмме как демо версия для пробы?

На постоянной основе не включен. 
Напишите мне в телеграмм @kochetovd, предоставлю на некоторое время.

> Отличный продукт. 

И спасибо за отзыв. Это вряд ли можно назвать продуктом, но как демонстрация работы - вполне =)
